try:
    print("Value of x is:" , x)
except:
    print("An exception occured")